baseurl = "https://manya-bansal.github.io/"
languageCode = "en-us"
title = "Manya Bansal"
publishDir = "docs"
theme = "hugo-theme-cactus"

canonifyurls = true
[params]
description = """ I am a computer science PhD student at MIT. I am advised by 
[Saman Amarasinghe](https://groups.csail.mit.edu/commit/) and [Jonathan Ragan-Kelley](https://people.csail.mit.edu/jrk/).
I am interested in designing extensible and productive languages (and tools!) 
for heterogeneous systems. 

I was previosuly an undergraduate at Stanford Univeristy studying mathematics (BS'23). At Stanford, I was incredibly fortunate to work 
with [Fredrik Kjolstad](http://fredrikbk.com/) and [Dawson Engler](https://web.stanford.edu/~engler/).

Email Me: manya227@csail.mit.edu 
"""
authorlocation = "authorlocation"
cover = "images/cover.png"
logo = "images/raspberry-pi.png"
email = "manya227@stanford.edu"
hideHUGOSupport = false
mainSectionTitle = "Research"
showAllPostsOnHomePage = true
showAllPostsArchive = true
tagsOverview = true # show tags overview by default.
tocInline = true

# [[menu.main]]
# name = "Home"
# url = "/"
# weight = 1


# [[menu.main]]
# name = "Research"
# url = "/"
# weight = 2

# [[menu.main]]
# name = "Personal"
# url = "/"
# weight = 3

# [[menu.main]]
# name = "Contact"
# url = "/"
# weight = 4



[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"