baseurl = "https://manya-bansal.github.io/"
languageCode = "en-us"
title = "Manya Bansal"
publishDir = "docs"
theme = "hugo-theme-cactus"
paginate = 2

canonifyurls = true
[params]
description = """I am an undergraduate student studying Mathematics at Stanford University. Somewhere along the way, 
I took a computer science class and became a permanent resident of the systems community. 

I am generally interested 
in designing extensible and productive languages (and tools!) for heterogeneous systems. 
At Stanford, I have been fortunate to work with [Fredrik Kjolstad](http://fredrikbk.com/) and [Dawson Engler](https://web.stanford.edu/~engler/).

"""
authorlocation = "authorlocation"
cover = "images/cover.png"
logo = "images/raspberry-pi.png"
email = "manya227@stanford.edu"
hideHUGOSupport = false
mainSectionTitle = "Research"
showAllPostsOnHomePage = true
showAllPostsArchive = true
tagsOverview = true # show tags overview by default.

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"